### ISSUE TITLE
Where to download backbone for Resnet models

### ISSUE THREAD

**Issue by soothingni** [open-mmlab/mmfashion#51]
Hi,

I was wondering if you also provided backbone files for Resnet models. I could only find one for Vgg at [Model_Zoo.md](https://github.com/open-mmlab/mmfashion/blob/master/docs/MODEL_ZOO.md). Would greatly appreciate some help in this area!

Thanks!

**Comment by veralauee** [comment]
The backbone checkpoints just follow imageNet pretrained pytorch model.
Please refer to this website https://pytorch.org/docs/stable/torchvision/models.html

**Comment by soothingni** [comment]
Got it! Thank you :)

**Comment by DaniellePerri1** [comment]
Hi, related this issue, I tried to download the pre-trained resnet18 model using pytorch, in order to run the comparability demo, as follows:

`import torch
import torchvision.models as models
resnet18 = models.resnet18(pretrained=True)
torch.save(resnet18, '/content/mmfashion/checkpoint/resnet18.pth')`

But when running the demo, I get the following RuntimeError:

>> RuntimeError: No state_dict found in checkpoint file checkpoint/resnet18.pth

In the other hand, when I download from the same path the original paper ("Learning_the_type_aware_embedding") downloaded in their code (https://download.pytorch.org/models/resnet18-5c106cde.pth), it indeed works but gives non-deterministic scores (e.g. first run give 1.94 score on set3, while another gives 0.241), and follows some warnings/error messages as describes in the following screenshot:

![image](https://user-images.githubusercontent.com/66483262/85171300-6bf08a80-b277-11ea-881a-ff854be2fe9f.png)

**My questions are:
1. Does the score should be non-deterministic? I've read the "type aware" paper, and all the parts look to be deterministic.
2. Should I get these error/warning?  
3. Can you please describes exactly from where you downloaded the Resnet18 model?**

Thanks in advance!
